#!/bin/sh -e
# TLS
hostname=$1
filename=$2
if [ -z "${hostname}" ] ; then
    echo 'Usage: genkey <hostname> [ <filename> ]'
    exit 1
fi
if [ -z "${filename}" ] ; then
    filename=rsa
fi
cd tls/.work
if [ ! -f ca.key ] ; then
    openssl genrsa -out ca.key 4096
    openssl req -new -x509 -days 720 -key ca.key -out ca.crt -config ca.conf
fi
mkdir -p  ../$hostname
cp ca.crt ../${hostname}/
rm -f server.csr server.key
openssl req -new -out server.csr -config ../../csr/${hostname}.conf
openssl x509 -req -days 720                       \
              -in server.csr                      \
              -CA ca.crt                          \
              -CAkey ca.key                       \
              -CAcreateserial                     \
              -out ../${hostname}/${filename}.crt \
              -extfile v3.ext
chmod 600 server.key
mv server.key ../${hostname}/${filename}.key
rm server.csr
