#!/usr/bin/perl
# ----------------------------------------------------------------------
# tachikoma server rsa keypair
# ----------------------------------------------------------------------
#

use strict;
use warnings;
use Tachikoma;

my $config = Tachikoma->configuration;

# Set our ID
$config->id('tachikoma@tachikoma');

# Set your unencrypted private key here
$config->private_key( q(-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
) );

$config->public_keys->{ $config->id } = {
    allow => {map {$_=>1} qw(
        command
        client
        server
    )},
    # allow_commands => {map {$_=>1} qw(
    #     connect_node
    # )},
    public_key =>
q(-----BEGIN RSA PUBLIC KEY-----
...
-----END RSA PUBLIC KEY-----
)};

1;
