#!/usr/bin/perl
# ----------------------------------------------------------------------
# $Id$
# ----------------------------------------------------------------------

use strict;
use warnings;
use Tachikoma;

my $config = Tachikoma->configuration;

# Set our ID
$config->id('tachikoma@tachikoma');

# Set your *unencrypted* private key here if desired.
# Otherwise, remove this and put the *encrypted* key in ~/.tachikoma/rsa
$config->private_key( q(-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
) );

$config->public_keys->{ $config->id } = {
    allow => {map {$_=>1} qw(
        command
        client
        server
    )},
    public_key =>
q(-----BEGIN RSA PUBLIC KEY-----
...
-----END RSA PUBLIC KEY-----
)};

1;
