#!/usr/bin/perl
# ----------------------------------------------------------------------
# $Id$
# ----------------------------------------------------------------------

use strict;
use warnings;
use Tachikoma::Config qw( $ID $Private_Key %Keys );

# Set our ID
$ID = 'tachikoma@tachikoma';

# Set your *unencrypted* private key here if desired.
# Otherwise, remove this and put the *encrypted* key in ~/.tachikoma/rsa
$Private_Key = q(-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----
);

$Keys{$ID} = {
    allow => {map {$_=>1} qw(
        command
        client
        server
    )},
    public_key =>
q(-----BEGIN RSA PUBLIC KEY-----
...
-----END RSA PUBLIC KEY-----
)};

1;
