#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::Nodes::ConsumerBroker;

my $home = ( getpwuid $< )[7];
Tachikoma->configuration->load_config_file(
    "$home/.tachikoma/etc/tachikoma.conf",
    '/usr/local/etc/tachikoma.conf',
);

my $topic    = $ARGV[0] or die "usage: get_count <topic> [ <group> ]\n";
my $group    = $ARGV[1] // "count";
my $consumer = Tachikoma::Nodes::ConsumerBroker->new( $topic, $group );
while (1) {
    my $group_cache = $consumer->get_group_cache;
    if ( $consumer->sync_error ) {
        print STDERR time, ' ', $consumer->sync_error;
        next;
    }
    my $total = 0;
    my $time  = time;
    printf "%d %-50s %10s\n", $time, 'PARTITION', 'COUNT';
    for my $partition_id ( sort keys %$group_cache ) {
        my $count = $group_cache->{$partition_id} // 0;
        printf "%d %-50s %10d\n", $time, $partition_id, $count;
        $total += $count;
    }
    printf "%d %-50s %10d\n", $time, 'TOTAL', $total;
    sleep( $ARGV[2] // 5 );
    print "\n";
}
