#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::Nodes::ConsumerBroker;

my $home = ( getpwuid $< )[7];
Tachikoma->configuration->load_config_file(
    "$home/.tachikoma/etc/tachikoma.conf",
    '/usr/local/etc/tachikoma.conf',
);

my $topic    = $ARGV[0] or die "usage: get_word_count <topic> [ <group> ]\n";
my $group    = $ARGV[1] // "word_count";
my $consumer = Tachikoma::Nodes::ConsumerBroker->new( $topic, $group );
my $group_cache = $consumer->get_group_cache;
if ( $consumer->sync_error ) {
    print STDERR $consumer->sync_error;
    exit 1;
}
my %total = ();
for my $partition_id ( sort keys %$group_cache ) {
    my $count = $group_cache->{$partition_id} or next;
    for my $word ( keys %$count ) {
        $total{$word} //= 0;
        $total{$word} += $count->{$word};
    }
}
my $i = 1;
for my $word ( sort { $total{$b} <=> $total{$a} } keys %total ) {
    printf "%-30s %10d\n", $word, $total{$word};
}
