#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::Nodes::ConsumerBroker;
use Tachikoma::Message qw( PAYLOAD );

my $home = ( getpwuid $< )[7];
Tachikoma->configuration->load_config_file(

my $topic      = $ARGV[0] or die "usage: sum_topic <topic> [ <group> ]\n";
my $group      = $ARGV[1] // "sum";
my $consumer   = Tachikoma::Nodes::ConsumerBroker->new( $topic, $group );
my $last_print = 0;
my $total      = 0;
$consumer->default_offset('start');
while (1) {
    my $messages = $consumer->fetch(
        sub {
            my ( $self, $message ) = @_;
            $self->{cache}->{count}++;
            $self->{cache}->{min} //= $message->[PAYLOAD];
            $self->{cache}->{min} = $message->[PAYLOAD]
                if ( $message->[PAYLOAD] < $self->{cache}->{min} );
            $self->{cache}->{max} = $message->[PAYLOAD]
                if ( $message->[PAYLOAD] > ( $self->{cache}->{max} // 0 ) );
            $self->{cache}->{sum} += $message->[PAYLOAD];
        }
    );
    if ( $consumer->sync_error ) {
        print STDERR time, ' ', $consumer->sync_error;
    }
    else {
        $total += scalar(@$messages);
        my $time = time;
        if ( $time - $last_print > 0 ) {
            print time, " received: $total\n";
            $last_print = $time;
            $total      = 0;
        }
    }
}
