#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::Nodes::Consumer;
use Tachikoma::Message qw( PAYLOAD );
require '/usr/local/etc/tachikoma.conf';

my $partition = $ARGV[0];
my $offsetlog = $ARGV[1];
die "usage: consume_stream <partition> [ <offsetlog> ]\n"
    if ( not $partition );
my $consumer = Tachikoma::Nodes::Consumer->new( $partition, $offsetlog );
while (1) {
    syswrite STDOUT, $_->[PAYLOAD] for ( @{ $consumer->fetch } );
    if ( $consumer->sync_error ) {
        print STDERR $consumer->sync_error;
    }
}
