#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::Nodes::Consumer;
use Tachikoma::Message qw( PAYLOAD );
require '/usr/local/etc/tachikoma.conf';

my $partition = $ARGV[0];
my $offsetlog = $ARGV[1];
die "usage: consume_batch <partition>\n" if ( not $partition );
my $consumer = Tachikoma::Nodes::Consumer->new( $partition, $offsetlog );
$consumer->default_offset('start');
while (1) {
    my $messages = $consumer->fetch;
    print $_->[PAYLOAD] for (@$messages);
    die $consumer->sync_error if ( $consumer->sync_error );
    last if ( $consumer->eos );
}
$consumer->commit_offset if ($offsetlog);
