#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::Nodes::Consumer;
use Data::Dumper;
require '/usr/local/etc/tachikoma.conf';
$Data::Dumper::Indent   = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Useperl  = 1;

my $partition = $ARGV[0];
die "usage: dump_messages <partition>\n" if ( not $partition );
my $consumer = Tachikoma::Nodes::Consumer->new($partition);
$consumer->default_offset('start');
$consumer->poll_interval(0.1);
while (1) {
    my $messages = $consumer->fetch;
    $_->payload for (@$messages);
    print Dumper($_) for (@$messages);
    die $consumer->sync_error if ( $consumer->sync_error );
}
