#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::Nodes::Consumer;
use Data::Dumper;

my $home = ( getpwuid $< )[7];
Tachikoma->configuration->load_config_file(
    "$home/.tachikoma/etc/tachikoma.conf",
    '/usr/local/etc/tachikoma.conf',
);

$Data::Dumper::Indent   = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Useperl  = 1;

my $partition = $ARGV[0];
my $offset    = $ARGV[1] // '-2';
die "usage: dump_message <partition> [ <offset> ]\n"
    if ( not defined $partition );
my $consumer = Tachikoma::Nodes::Consumer->new($partition);
$consumer->next_offset($offset);
my $message = $consumer->fetch->[0];
$message->payload if ($message);
print Dumper($message);
die $consumer->sync_error if ( $consumer->sync_error );
