#!/usr/bin/env perl
use strict;
use warnings;
use Accessories::Forks;
use Data::Dumper;

my $forks = Accessories::Forks->new;

my $map = <<'EOF';
    my $self    = shift;
    my $message = shift;
    return [ sort keys %$self ];
EOF

print "The following fields are reserved: ";

$forks->farm(
    1,
    ['test'],
    $map,
    sub {
        my $item   = shift;
        my $output = shift;
        print join( ', ', @$output ), "\n";
    }
);
