#!/usr/bin/env perl
use strict;
use warnings;
use Accessories::Forks;

my $forks = Accessories::Forks->new;

my @hosts = @ARGV;
my @up_hosts = ();

print "checking hosts with ping...\n";
my $start    = Time::HiRes::time;
my @commands = ();
for my $host (@hosts) {
    push( @commands, "ping -c 1 $host" );
}

$forks->spawn(
    8,
    \@commands,
    sub {
        my $command = shift;
        my $output  = shift;
        my $host    = ( split( ' ', $command, 4 ) )[3];
        if ( $output =~ m([1-9] packets received) ) {
            print "$host: up\n";
            push @up_hosts, $host;
        }
        else {
            print "$host: down\n";
        }
    }
);
printf "took: %.3f seconds\n", Time::HiRes::time - $start;
print "\n";

# ----------------------------------------------------------------

print "running remote commands...\n";
@commands = ();
for my $host (@up_hosts) {
    push( @commands, "ssh $host date" );
}

$forks->spawn(
    8,
    \@commands,
    sub {
        my $command = shift;
        my $output  = shift;
        my $host    = ( split( ' ', $command, 3 ) )[1];
        print "$host: $output";
    }
);
