#!/usr/bin/env perl
use strict;
use warnings;
use Accessories::Forks;

my $count = shift @ARGV // 8;
my $forks = Accessories::Forks->new;
my @commands = <>;
$forks->spawn(
    $count,
    \@commands,
    sub {
        my ( $cmd, $out ) = @_;
        chomp $cmd;
        chomp $out;
        print "+ $cmd\n$out\n";
    }
);
