#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma;
use Tachikoma::Message qw( TM_BYTESTREAM );
require '/usr/local/etc/tachikoma.conf';
my $tachikoma = Tachikoma->inet_client( 'localhost', 4231, 'use_SSL' );
my $request = Tachikoma::Message->new;
$request->type(TM_BYTESTREAM);
$request->to("echo");
$request->payload("hello, world\n");
$tachikoma->callback(
    sub {
        my $response = shift;
        print $response->payload;
        return;
    }
);
$tachikoma->fill($request);
$tachikoma->drain;
