#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::EventFrameworks::Select;
use Tachikoma::Nodes::Router;
use Tachikoma::Nodes::Callback;
use Tachikoma::Nodes::Socket qw( TK_R TK_SYNC );
use Tachikoma::Message qw( TM_BYTESTREAM );

my $home = ( getpwuid $< )[7];
Tachikoma->configuration->load_config_file(
    "$home/.tachikoma/etc/tachikoma.conf",
    '/usr/local/etc/tachikoma.conf',
);
Tachikoma->event_framework( Tachikoma::EventFrameworks::Select->new );

my $tachikoma =
    Tachikoma::Nodes::Socket->inet_client( 'localhost', 4230, TK_SYNC );
my $router = Tachikoma::Nodes::Router->new;
my $request = Tachikoma::Message->new;
$request->type(TM_BYTESTREAM);
$request->to("echo");
$request->payload("hello, world\n");
my $get_response = Tachikoma::Nodes::Callback->new(
    sub {
        my $response = shift;
        print $response->payload;
        $router->stop;
        return;
    }
);
$tachikoma->sink($get_response);
$tachikoma->fill($request);
$router->drain;
