#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::Nodes::ConsumerBroker;
use Data::Dumper;

my $home = ( getpwuid $< )[7];
Tachikoma->configuration->load_config_file(
    "$home/.tachikoma/etc/tachikoma.conf",
    '/usr/local/etc/tachikoma.conf',
);

$Data::Dumper::Indent   = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Useperl  = 1;

my $topic    = $ARGV[0];
my $group    = $ARGV[1] or die "usage: dump_topic_cache <topic> <group>\n";
my $consumer = Tachikoma::Nodes::ConsumerBroker->new( $topic, $group );
print Dumper( $consumer->get_group_cache );
if ( $consumer->sync_error ) {
    print STDERR $consumer->sync_error;
    exit 1;
}
