#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::Nodes::ConsumerBroker;
require '/usr/local/etc/tachikoma.conf';

my $topic     = $ARGV[0] or die "usage: get_broker_id <topic> <partition>\n";
my $i         = $ARGV[1] // 0;
my $broker    = Tachikoma::Nodes::Topic->new($topic);
my $broker_id = $broker->get_partitions->[$i];
if ($broker_id) {
    print "$broker_id\n";
}
else {
    print STDERR "ERROR: no such partition\n";
}
