#!/usr/bin/env perl
use strict;
use warnings;
use Tachikoma::Nodes::ConsumerBroker;
require '/usr/local/etc/tachikoma.conf';

my $topic      = $ARGV[0] or die "usage: list_partitions <topic>\n";
my $broker     = Tachikoma::Nodes::Topic->new($topic);
my $partitions = $broker->get_partitions;
for my $i ( 0 .. $#{$partitions} ) {
    printf "%4d %s\n", $i, $partitions->[$i];
}
